// Planet surface textures (Solar System Scope, CC BY 4.0) → assets/textures.js (data-URI bundle so file:// works).
import fs from 'node:fs';
import path from 'node:path';
import { RAW, ROOT, ensureFile, log, warn, head, fmtBytes, flags, problems } from './util.mjs';

const STEMS = {
  sun: ['sun'], mercury: ['mercury'], venus: ['venus_surface', 'venus_atmosphere'], earth: ['earth_daymap', 'earth_nightmap', 'earth_clouds'],
  moon: ['moon'], mars: ['mars'], jupiter: ['jupiter'], saturn: ['saturn'], uranus: ['uranus'], neptune: ['neptune'],
};
const RES_ORDER = ['8k', '4k', '2k'];

function isImage(buf) {
  return (buf[0] === 0xff && buf[1] === 0xd8) || (buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47);
}

export async function buildTextures(cfg) {
  head('TEXTURES');
  const tc = cfg.textures;
  if (!tc.enabled || flags.skipTextures) { log('  skipped (textures.enabled=false or --skip-textures)'); return { stats: { skipped: true } }; }
  const dir = path.join(RAW, 'textures'); fs.mkdirSync(dir, { recursive: true });
  const out = {}; const used = []; const missing = [];
  const want = [];
  for (const [body, stems] of Object.entries(STEMS)) for (const stem of stems) want.push({ body, stem, pref: tc.resolution[stem] || tc.resolution[body] || '2k', ext: 'jpg' });
  want.push({ body: 'saturn', stem: 'saturn_ring_alpha', pref: '2k', ext: 'png' });
  for (const w of want) {
    const order = [w.pref, ...RES_ORDER.filter((r) => r !== w.pref && parseInt(r) < parseInt(w.pref))];
    const before = problems.length;
    let got = null;
    for (const res of order) {
      const file = `${res}_${w.stem}.${w.ext}`;
      const dest = path.join(dir, file);
      const ok = await ensureFile({ dataset: `texture ${file}`, url: cfg.sources.textureBase + file, dest, required: false, minBytes: 5000,
        note: `Optional planet texture. Download from https://www.solarsystemscope.com/textures/ and save as data/raw/textures/${file}` });
      if (ok) {
        const buf = fs.readFileSync(dest);
        if (isImage(buf)) { got = { file, buf, res }; break; }
        warn(`${file} is not an image; discarding`); fs.rmSync(dest, { force: true });
      }
      // a failed attempt at this resolution was recorded as a problem; drop it if a lower one works
    }
    if (got) {
      problems.splice(before, problems.length - before);   // a lower resolution worked, so the failed attempts are not a problem
      out[w.stem] = `data:image/${w.ext === 'png' ? 'png' : 'jpeg'};base64,${got.buf.toString('base64')}`;
      used.push({ stem: w.stem, file: got.file, bytes: got.buf.length, res: got.res });
    } else missing.push(w.stem);
  }
  if (!Object.keys(out).length) return { stats: { count: 0, missing }, missing };
  fs.mkdirSync(path.join(ROOT, 'assets'), { recursive: true });
  const jsPath = path.join(ROOT, 'assets', 'textures.js');
  fs.writeFileSync(jsPath, `// generated by tools/build-data.mjs — planet textures as data URIs (Solar System Scope, CC BY 4.0)\nwindow.__SIMTEX = ${JSON.stringify(out)};\n`);
  log(`  ${used.length} textures packed → assets/textures.js (${fmtBytes(fs.statSync(jsPath).size)})`);
  return { stats: { count: used.length, files: used, missing }, missing };
}
